#!/bin/bash
# Setup cron jobs for the Mining Intelligence Platform
# - News fetching every 15 minutes
# - Extraction triggers every 30 minutes
# - Extraction worker every hour

# Get the absolute path to the data-pipeline directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON_PATH="$SCRIPT_DIR/venv/bin/python"

# Script paths
FETCH_SCRIPT="$SCRIPT_DIR/fetch_news.py"
TRIGGER_SCRIPT="$SCRIPT_DIR/extraction_trigger.py"
EXTRACTION_SCRIPT="$SCRIPT_DIR/run_extraction.py"
QUARTERLY_SCRIPT="$SCRIPT_DIR/fetch_quarterly_reports.py"
METAL_PRICES_SCRIPT="$SCRIPT_DIR/fetch_metal_prices.py"
STOCK_PRICES_SCRIPT="$SCRIPT_DIR/fetch_stock_prices.py"

# Log files
NEWS_LOG="$SCRIPT_DIR/logs/news_fetch.log"
TRIGGER_LOG="$SCRIPT_DIR/logs/extraction_trigger.log"
EXTRACTION_LOG="$SCRIPT_DIR/logs/extraction.log"
QUARTERLY_LOG="$SCRIPT_DIR/logs/quarterly_reports.log"
METAL_PRICES_LOG="$SCRIPT_DIR/logs/metal_prices.log"
STOCK_PRICES_LOG="$SCRIPT_DIR/logs/stock_prices.log"

# Create logs directory
mkdir -p "$SCRIPT_DIR/logs"

# Verify paths exist
if [ ! -f "$PYTHON_PATH" ]; then
    echo "Error: Python not found at $PYTHON_PATH"
    echo "Please run: python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt"
    exit 1
fi

# Generate cron entries
CRON_NEWS="*/15 * * * * cd $SCRIPT_DIR && $PYTHON_PATH $FETCH_SCRIPT >> $NEWS_LOG 2>&1"
CRON_TRIGGER="*/30 * * * * cd $SCRIPT_DIR && $PYTHON_PATH $TRIGGER_SCRIPT >> $TRIGGER_LOG 2>&1"
CRON_EXTRACTION="0 * * * * cd $SCRIPT_DIR && $PYTHON_PATH $EXTRACTION_SCRIPT --worker >> $EXTRACTION_LOG 2>&1"
CRON_QUARTERLY="0 6 * * * cd $SCRIPT_DIR && $PYTHON_PATH $QUARTERLY_SCRIPT --all --limit 50 >> $QUARTERLY_LOG 2>&1"
CRON_METAL_PRICES="*/15 * * * * cd $SCRIPT_DIR && $PYTHON_PATH $METAL_PRICES_SCRIPT >> $METAL_PRICES_LOG 2>&1"
CRON_STOCK_PRICES="*/15 * * * * cd $SCRIPT_DIR && $PYTHON_PATH $STOCK_PRICES_SCRIPT >> $STOCK_PRICES_LOG 2>&1"

echo "=============================================="
echo "Mining Intelligence Platform - Cron Setup"
echo "=============================================="
echo ""
echo "The following cron jobs will be configured:"
echo ""
echo "1. NEWS FETCH (every 15 minutes)"
echo "   Fetches news from TMX Newsfile, GlobeNewswire, etc."
echo "   $CRON_NEWS"
echo ""
echo "2. EXTRACTION TRIGGER (every 30 minutes)"
echo "   Scans news for earnings/technical report keywords"
echo "   Adds matching articles to extraction queue"
echo "   $CRON_TRIGGER"
echo ""
echo "3. EXTRACTION WORKER (every hour)"
echo "   Processes pending extraction jobs"
echo "   Extracts production data and mineral estimates"
echo "   $CRON_EXTRACTION"
echo ""
echo "4. QUARTERLY REPORTS FETCH (daily at 6am)"
echo "   Downloads quarterly reports from news sources"
echo "   Queues PDFs for extraction"
echo "   $CRON_QUARTERLY"
echo ""
echo "5. METAL PRICES (every 15 minutes)"
echo "   Fetches gold, silver, copper, platinum, palladium, uranium prices"
echo "   Updates metal_prices table for API consumption"
echo "   $CRON_METAL_PRICES"
echo ""
echo "6. STOCK PRICES (every 15 minutes)"
echo "   Fetches live stock prices for all mining companies"
echo "   Updates current_price, day_change, day_change_percent"
echo "   $CRON_STOCK_PRICES"
echo ""
echo "=============================================="
echo ""
echo "To add these cron jobs manually:"
echo "  crontab -e"
echo ""
echo "Then add these lines:"
echo ""
echo "# Mining Intelligence Platform"
echo "$CRON_NEWS"
echo "$CRON_TRIGGER"
echo "$CRON_EXTRACTION"
echo "$CRON_QUARTERLY"
echo "$CRON_METAL_PRICES"
echo "$CRON_STOCK_PRICES"
echo ""
echo "=============================================="
echo ""
echo "Or to add all automatically, run:"
echo ""
cat << 'SCRIPT'
(crontab -l 2>/dev/null | grep -v 'fetch_news.py' | grep -v 'extraction_trigger.py' | grep -v 'run_extraction.py' | grep -v 'fetch_quarterly_reports.py' | grep -v 'fetch_metal_prices.py' | grep -v 'fetch_stock_prices.py'
echo "# Mining Intelligence Platform - News Fetch (every 15 min)"
echo "*/15 * * * * cd $SCRIPT_DIR && $PYTHON_PATH $FETCH_SCRIPT >> $NEWS_LOG 2>&1"
echo "# Mining Intelligence Platform - Extraction Trigger (every 30 min)"
echo "*/30 * * * * cd $SCRIPT_DIR && $PYTHON_PATH $TRIGGER_SCRIPT >> $TRIGGER_LOG 2>&1"
echo "# Mining Intelligence Platform - Extraction Worker (hourly)"
echo "0 * * * * cd $SCRIPT_DIR && $PYTHON_PATH $EXTRACTION_SCRIPT --worker >> $EXTRACTION_LOG 2>&1"
echo "# Mining Intelligence Platform - Quarterly Reports Fetch (daily at 6am)"
echo "0 6 * * * cd $SCRIPT_DIR && $PYTHON_PATH $QUARTERLY_SCRIPT --all --limit 50 >> $QUARTERLY_LOG 2>&1"
echo "# Mining Intelligence Platform - Metal Prices (every 15 min)"
echo "*/15 * * * * cd $SCRIPT_DIR && $PYTHON_PATH $METAL_PRICES_SCRIPT >> $METAL_PRICES_LOG 2>&1"
echo "# Mining Intelligence Platform - Stock Prices (every 15 min)"
echo "*/15 * * * * cd $SCRIPT_DIR && $PYTHON_PATH $STOCK_PRICES_SCRIPT >> $STOCK_PRICES_LOG 2>&1"
) | crontab -
SCRIPT
echo ""
echo "=============================================="
echo ""
echo "To verify cron jobs were added:"
echo "  crontab -l"
echo ""
echo "To test scripts manually:"
echo "  cd $SCRIPT_DIR && $PYTHON_PATH $FETCH_SCRIPT"
echo "  cd $SCRIPT_DIR && $PYTHON_PATH $TRIGGER_SCRIPT --dry-run"
echo "  cd $SCRIPT_DIR && $PYTHON_PATH $EXTRACTION_SCRIPT --stats"
echo "  cd $SCRIPT_DIR && $PYTHON_PATH $QUARTERLY_SCRIPT --ticker AEM"
echo "  cd $SCRIPT_DIR && $PYTHON_PATH $METAL_PRICES_SCRIPT"
echo "  cd $SCRIPT_DIR && $PYTHON_PATH $STOCK_PRICES_SCRIPT"
echo ""
echo "To check logs:"
echo "  tail -f $NEWS_LOG"
echo "  tail -f $TRIGGER_LOG"
echo "  tail -f $EXTRACTION_LOG"
echo "  tail -f $QUARTERLY_LOG"
echo "  tail -f $METAL_PRICES_LOG"
echo "  tail -f $STOCK_PRICES_LOG"
echo ""
